# Generated by Django 4.0.3 on 2022-03-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='project_img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='category',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='project_url',
        ),
    ]
