# Generated by Django 4.0.3 on 2022-03-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_project_img_category_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=256, verbose_name='Url'),
        ),
    ]
