# Generated by Django 4.0.3 on 2022-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=256)),
                ('img', models.ImageField(upload_to='project/%Y/%m/%d')),
                ('project_url', models.TextField(blank=True, null=True)),
                ('github_url', models.TextField()),
            ],
        ),
    ]
