# Generated by Django 4.0.3 on 2022-03-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options_alter_category_img_and_more'),
        ('core', '0002_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.TextField(verbose_name='Url do Github'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.TextField(blank=True, null=True, verbose_name='Url do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=256, verbose_name='Url'),
        ),
    ]
